# driver config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/prompthub_db
    username: root
    password: root

# mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml
